name: meds_at_home
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_pro: ^1.0.0
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  google_sign_in: ^4.2.0
  firebase_storage: ^3.1.3
  shared_preferences: ^0.5.6+1
  image_picker: ^0.6.3+4
  font_awesome_flutter: ^8.5.0
  firebase_database: ^3.1.3
  intl: ^0.15.7
  uuid: ^2.0.4
  firebase_core: ^0.4.0
  provider: ^4.0.4
  numberpicker: ^1.2.0
  splashscreen: ^1.2.0
  linear_gradient: ^0.1.12
  fluttertoast: ^3.1.3
  timeago: ^2.0.26
  sliding_up_panel: ^1.0.2
  carousel_slider: ^2.1.0
  photo_view: ^0.9.2
  cupertino_icons: ^0.1.3
  animated_splash_screen: ^1.0.0+1
  dio:
  get: ^3.8.0
  page_transition: ^1.1.6
  auto_size_text: ^2.1.0
  firebase_auth_web:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - images/
    - images/cats/b1.png
    - images/cats/b4.png
    - images/cats/b8.png
    - images/cats/fristaid.png
    - images/cats/injec.png
    - images/cats/skins.png
    - images/cats/tablets.png
    - images/cats/vitamins.jfif
    - images/a1.jfif
    - images/a3.jfif
    - images/a2.jfif
    - images/a4.jfif
    - images/a5.jfif
    - images/back1.webp
    - images/back2.jpeg
    - images/logo.png
    - images/product/c1.jfif
    - images/product/c2.jfif
    - images/product/c3.jfif
    - images/product/c4.jfif
    - images/product/c5.jfif
    - images/product/c6.jfif
    - images/product/c7.jfif
    - images/product/c8.jfif
    - images/product/c9.jfif
    - images/product/c10.jfif

